# ------------------------------------------------------------------
# R Script for Correlation Analysis of MASLD Metadata and Ferroptosis Scores
# ------------------------------------------------------------------
# This script will:
# 1. Load the harmonized MASLD metadata.
# 2. Load the GSVA ferroptosis scores generated by the previous script.
# 3. Merge the metadata with the ferroptosis scores based on sample IDs.
# 4. Calculate Pearson and Spearman correlations between numeric metadata
#    features and the ferroptosis scores.
# 5. Output a final, tidy data frame with all correlation results.
# ------------------------------------------------------------------

# Step 1: Install and Load Required Libraries
if (!require("dplyr", quietly = TRUE)) install.packages("dplyr")
if (!require("tidyr", quietly = TRUE)) install.packages("tidyr")

library(dplyr)
library(tidyr)

# --- Data Loading and Preparation ---

# Step 2: Load Harmonized Metadata
# This file is the primary source of clinical metadata for each sample.
cat("Loading harmonized metadata...\n")
metadata_file <- "harmonized_MASLD_metadata.csv"
if (!file.exists(metadata_file)) {
  stop("FATAL: Metadata file not found! Please ensure 'harmonized_MASLD_metadata.csv' is in the working directory.")
}
metadata <- read.csv(metadata_file)


# Step 3: Load the Ferroptosis Score File
# This specifically loads the output from your previous GSVA script.
cat("Loading ferroptosis score file...\n")
scores_file <- "pathway_analysis_RESULTS/harmonized_ferroptosis_GSVA_scores.csv"
if (!file.exists(scores_file)) {
  stop("FATAL: GSVA scores file not found! Please run the previous script to generate it.")
}
ferroptosis_scores <- read.csv(scores_file)


# Step 4: Merge Metadata with Ferroptosis Scores
# We will merge the two data frames using their common sample identifier.
cat("Merging metadata with scores...\n")

# Perform an inner join to create the final analysis table.
# This ensures that we only analyze samples present in BOTH files.
merged_data <- inner_join(metadata, ferroptosis_scores, by = c("sample_id" = "SampleID"))

cat(paste("Successfully merged data. Total samples for analysis:", nrow(merged_data), "\n\n"))


# --- Correlation Analysis ---

# Step 5: Define the variables for correlation
# We select the numeric metadata features and the ferroptosis scores to be analyzed.
numeric_meta_features <- c("fibrosis_stage", "age", "bmi")
ferroptosis_score_types <- c("GSVA_Drivers_Score", "GSVA_Suppressors_Score")

# Create an empty list to store the results from each correlation test.
correlation_results_list <- list()

cat("Calculating Pearson and Spearman correlations...\n")

# Step 6: Loop through each feature and score to calculate correlations
for (feature in numeric_meta_features) {
  for (score in ferroptosis_score_types) {

    # Skip if the feature or score column does not exist
    if (!feature %in% colnames(merged_data) || !score %in% colnames(merged_data)) {
      cat(paste("Warning: Skipping combination", feature, "-", score, "as one column is missing.\n"))
      next
    }

    # Skip if there are not enough complete pairs of data points to test
    complete_cases <- sum(complete.cases(merged_data[, c(feature, score)]))
    if (complete_cases < 3) {
      cat(paste("Skipping", feature, "vs.", score, "due to insufficient complete data pairs (", complete_cases, ").\n"))
      next
    }

    # Calculate Pearson correlation
    pearson_test <- cor.test(merged_data[[feature]], merged_data[[score]],
                             method = "pearson", use = "pairwise.complete.obs")

    # Calculate Spearman correlation
    spearman_test <- cor.test(merged_data[[feature]], merged_data[[score]],
                              method = "spearman", use = "pairwise.complete.obs", exact = FALSE)

    # Store the results in a temporary data frame
    temp_results <- data.frame(
      Metadata_Feature = feature,
      Ferroptosis_Score_Type = score,
      Pearson_Correlation = pearson_test$estimate,
      Pearson_P_Value = pearson_test$p.value,
      Spearman_Correlation = spearman_test$estimate,
      Spearman_P_Value = spearman_test$p.value
    )

    # Add the temporary results to our list
    correlation_results_list[[length(correlation_results_list) + 1]] <- temp_results
  }
}

# --- Final Output ---

# Step 7: Combine all results into a single data frame and display
cat("Correlation analysis complete. Finalizing results...\n")

if (length(correlation_results_list) > 0) {
  # Combine the list of results into a single, clean data frame
  final_correlation_table <- bind_rows(correlation_results_list) %>%
    # Arrange the results by the Spearman p-value to see the most significant correlations first
    arrange(Spearman_P_Value) %>%
    # Round the numeric columns for better readability
    mutate(across(where(is.numeric), ~ round(., 4)))

  # Print the final table to the console
  cat("\n--- Correlation Results between Metadata and Ferroptosis Scores ---\n")
  print(final_correlation_table)
  cat("------------------------------------------------------------------\n")

  # Optionally, save the results to a CSV file
  output_filename <- "metadata_ferroptosis_correlation_results.csv"
  write.csv(final_correlation_table, output_filename, row.names = FALSE)
  cat(paste("\n✅ Success! Results have been saved to:", output_filename, "\n"))

} else {
  cat("\nNo correlation results were generated. Please check your input files for data.\n")
}
