suppressPackageStartupMessages(library(fgsea))
setwd("/Users/subhadipbanerjee/masld-revision")
rk <- read.csv("results/ws11/ranked_t.csv"); rnk <- sort(setNames(rk$t, rk$GeneSymbol), decreasing=TRUE)
gs <- jsonlite::fromJSON("results/ws11/genesets_for_fgsea.json", simplifyVector=FALSE)
paths <- lapply(gs, function(x) unlist(x))
fg <- as.data.frame(fgseaMultilevel(paths, rnk, minSize=10, maxSize=Inf))
fg$leadingEdge <- sapply(fg$leadingEdge, paste, collapse=",")
write.csv(fg, "results/ws11/fgsea_all_modalities.csv", row.names=FALSE)
print(fg[,c("pathway","NES","pval","padj","size")])
